### PR TITLE
refactor(plugins): nudge plugins own their model/subagent policy; surface only callSite

### PR DESCRIPTION
**Pull request by siddseethepalli**
## Summary

- `task-progress-nudge` and `exploration-drift` reached into host singletons (`findConversation`, `getSubagentManager`) on the post-tool-use hot path to learn the turn's **call site**, the client's **dynamic-UI capability**, and whether the run is a **subagent**. This surfaces those three signals on `PostToolUseContext` — populated by the agent loop from run-options the daemon already knows — so the plugins read context instead of importing host internals.
- **`PostToolUseContext`** gains `callSite`, `supportsDynamicUi`, `isSubagent`. **`AgentLoopRunOptions`** gains optional `supportsDynamicUi`/`isSubagent` (defaults `true`/`false`); `daemon/conversation-agent-loop.ts` populates them from the `Conversation`. **`@vellumai/plugin-api`** re-exports `isWeakOpenModel` (a shared host predicate, also used by `ui-surface`/`cli`), so the plugin stops importing it from `providers/`.
- Both plugins drop their lazy host imports + registry/subagent module-graph coupling; **both are now fully clean** (plugin-api + their own files) and removed from the import-boundary guard baseline.
- **No behavior change.** `tsc --noEmit` clean; eslint/prettier clean; the two hook test suites (rewritten to drive gates via context fields, no host mocks) plus `tool-error`/`tool-result-truncate`/guard all pass (48 tests). Net −37 lines — the plugins got simpler.

## Original prompt

Continuing the plugin import-boundary cleanup (after #36421/#36424/#36425/#36427), leaving the two memory plugins for the in-progress retrieval refactor, the `exploration-drift` + `task-progress-nudge` pair was next — they share the "am I a subagent?" coupling. Per the agreed design, the fix enriches the hook context rather than exposing host singletons. `isWeakOpenModel` is re-exported as-is (kept the name — see PR comment).

## Verify

- Affected suites: `bun test src/__tests__/{task-progress-nudge-hook,exploration-drift-hook,tool-error-hook,tool-result-truncate-hook,plugin-import-boundary-guard}.test.ts` → 48 pass.
- The agent-loop suite reports 111 failures when its 19 files run in a single `bun test` process — that's the known cross-file `mock.module` leak (identical count on clean `main`); each file passes individually.

### CODE REVIEW

**Comment by siddseethepalli** [comment]
**Where to focus review** (touches the core loop + the public plugin-api contract; behavior-preserving refactor):

The three new `PostToolUseContext` signals replace host-singleton lookups in the two nudge plugins. The equivalences to confirm:

1. **`callSite` gate** — plugins now check `ctx.callSite !== "mainAgent"` (the same pattern `empty-response`/`surface-completion-nudge` already use on `PostModelCallContext`). On the daemon path `turnCallSite` defaults to `"mainAgent"`, so this matches the old `conversation.currentCallSite` check; workflow leaves (no `callSite` run-option → `null`) skip here, matching the old "conversation not found → return".
2. **`supportsDynamicUi`** — daemon computes `!(caps?.supportsDynamicUi === false)` from `currentTurnChannelCapabilities ?? channelCapabilities`, i.e. the exact old skip condition.
3. **`isSubagent`** — now the `Conversation.isSubagent` flag instead of `getSubagentManager().getParentInfo(id) !== undefined`. These are set together in `subagent/manager.ts` (it calls `setIsSubagent(true)` where it registers the child), so they should agree — the one signal that swapped source, worth a confirm.

`isWeakOpenModel` re-exported as-is — kept the name (the pattern is open-weight-only, so `isWeakModel` would overpromise). A rename, if wanted, is a separate mechanical PR.

Note: the agent-loop test suite shows 111 fails when its 19 files run in one `bun test` process — pre-existing cross-file `mock.module` leak (identical count on clean `main`); each file passes individually.

File: assistant/src/agent/loop.ts [hunk 1]
```diff
@@ -2162,6 +2175,9 @@ export class AgentLoop {
             additionalContext: null,
             model: response.model,
             maxInputTokens: contextWindowTokens,
+            callSite: callSite ?? null,
+            supportsDynamicUi,
```
[the remark this answers is not in the document]
Comment (siddseethepalli) [reply assistant/src/agent/loop.ts:2173]: Good catch — valid P2, fixed in 532620fc87.

`wakeAgentForOpportunity` was the third `agentLoop.run()` caller (alongside the main turn loop and `leaf-runner`); it defaults `callSite` to `mainAgent` but wasn't passing `supportsDynamicUi`, so a wake on a non-UI channel could be nudged to `ui_show`.

Rather than duplicate the derivation, I extracted it into `Conversation.agentLoopRunGates()` (returns `{ supportsDynamicUi, isSubagent }` from the live `channelCapabilities`/`isSubagent`) and spread it on both daemon run paths so they can't drift again. `leaf-runner` stays on defaults — it has no Conversation and uses a non-main call site, so the call-site gate already covers it.

**Comment by siddseethepalli** [comment]
@codex review

**Comment by siddseethepalli** [comment]
CI was failing: the `Conversation.agentLoopRunGates()` method (from the P2 fix) threw `TypeError: agentLoopRunGates is not a function` on the hand-rolled `Conversation` doubles in the `agent-wake` and `conversation-agent-loop` test suites — an absent method on a partial double is a hard failure, and that brittleness would recur for every future double.

Fixed in `c9210095745d1d5b1df6c6f495f64c8adfacdf3a` by converting it to a dependency-free leaf function (`daemon/agent-loop-run-gates.ts`) — a pure projection of the conversation's public `channelCapabilities`/`isSubagent` fields with a type-only `Conversation` import. Absent fields fall through to the existing safe defaults, so partial doubles work unmodified (and now exercise the real derivation instead of a hardcoded stub). Both run-path callers spread the free function; the method and the test stub are gone.

Verified locally: the 4 originally-failing files pass grouped (82) and individually, plus the guard + PostToolUseContext hook tests (60).

@codex review

**Comment by siddseethepalli** [comment]
Rebased onto `main` (now includes #36436). **Dropped the `isWeakOpenModel` plugin-api re-export** — `task-progress-nudge` now gates on `ctx.needsFirmerSteering` (the host-computed boolean from #36436) instead of calling the predicate itself.

Net effect on this PR's public surface: it now adds **only** the three context fields (`callSite` / `supportsDynamicUi` / `isSubagent`) to `PostToolUseContext` — no re-exported model-taxonomy predicate. `plugin-api/index.ts` is back to its main state.

Rebase notes:
- `loop.ts` and `types.ts` auto-merged cleanly (the construction site carries all four fields: `needsFirmerSteering` + the three gates).
- Hand-resolved `task-progress-nudge` hook (combined doc framing; removed the now-unused `isWeakOpenModel` import) and its test (`makeCtx` now takes `needsFirmerSteering` + `gates`).
- Guard baseline: `task-progress-nudge` and `exploration-drift` are now fully clean (removed from baseline); `documents`/`session` retained. Guard test green.

Verified locally: task-progress (10), exploration-drift (23), tool-error (8), tool-result-truncate (4), guard (2), weak-open-model (3), plus the wake/leaf suites (agent-wake 62, conversation-agent-loop 65, +overflow/inference-profile/override-profile). Typecheck clean.

Commit `ec77b7bbdbbbce94d7c2c8229506fec135089056`. @codex review

File: assistant/src/plugin-api/types.ts [hunk 2]
```diff
@@ -373,6 +373,26 @@ export interface PostToolUseContext {
    * receiving a precomputed limit.
    */
   readonly maxInputTokens: number;
+  /**
+   * Call site of the run this tool executed under (e.g. `"mainAgent"`), or
+   * `null` when the run carries no call-site tag. A hook that should act only
+   * on the user-facing main-agent turn — not background or subagent runs —
+   * gates on this.
+   */
+  readonly callSite: LLMCallSite | null;
```
Comment (dvargasfuertes) [inline assistant/src/plugin-api/types.ts:370]: 🚢  - we have this in other contexts

File: assistant/src/plugin-api/types.ts [hunk 3]
```diff
@@ -373,6 +373,26 @@ export interface PostToolUseContext {
...
+  /**
+   * Whether the connected client can render dynamic UI surfaces (`ui_show`).
+   * `false` when the channel explicitly lacks the capability; `true` when it is
+   * supported or unknown. A hook that would prompt the model to show a surface
+   * skips when this is `false`.
+   */
+  readonly supportsDynamicUi: boolean;
```
Comment (dvargasfuertes) [inline assistant/src/plugin-api/types.ts:379]: I would remove this. I'd argue that the task plugin shouldn't care whether a client is connected or not, and in fact, that may even change between the start of the hook and the end of the hook. the task plugin can just emit ui_show or task progress or whatever, and it's up to the caller/client to decide what to do with it.

To quote Sidd: "A method shouldn't care about who's calling it"

File: assistant/src/plugin-api/types.ts [hunk 4]
```diff
@@ -373,6 +373,26 @@ export interface PostToolUseContext {
...
+  /**
+   * Whether this run is a subagent — a child investigation/worker with no live
+   * user watching. Hooks whose nudges only make sense for a user-facing turn
+   * skip when this is `true`.
+   */
+  readonly isSubagent: boolean;
```
Comment (dvargasfuertes) [inline assistant/src/plugin-api/types.ts]: is this not redundant with `callSite`? if it isn't, should it be?

**Comment by siddseethepalli** [comment]
Reworked per review — thanks @dvargasfuertes, this is a cleaner contract. Force-pushed `0936a87177`.

**`needsFirmerSteering` (from #36436) — reverted.** You're right it's an opinionated, imprecise heuristic masquerading as a general turn property (true for opus-level glm-5.2, false for weak models the regex omits). task-progress-nudge now owns the model policy inline (`NUDGE_TARGET_MODEL_PATTERN`, matched on `ctx.model`) — the same shape exploration-drift already uses for its loop-prone set. Regex unchanged for now (behavior-preserving), but it's plugin-local so the glm-5.2 case is trivial to tune there.

**`supportsDynamicUi` — removed.** Agreed — the nudge is advisory and self-degrades (its text offers a one-line-note fallback), so it needn't gate on client capability.

**`isSubagent` — dropped the field.** Subagents run under `callSite: "subagentSpawn"` (manager.ts:649), so exploration-drift exempts them via `ctx.callSite === "subagentSpawn"`, and task-progress's `callSite === "mainAgent"` gate already excludes them. It was redundant — gone.

**`callSite` — kept** (the field you 🚢'd); it's the only thing PostToolUseContext gains now.

Net: both nudge plugins are fully self-contained (no lazy host imports), so they drop out of the import-boundary baseline. Diff is ~100 lines smaller.

@codex review

**Comment by siddseethepalli** [comment]
Good catch on the queued-subagent case — verified: a subagent spawn passes `callSite: "subagentSpawn"` explicitly, but a follow-up enqueued while the subagent is busy drains through the generic queue path (`conversation-process.ts:930`) with no call site, defaulting to `mainAgent` (`conversation-agent-loop.ts:342`). So queued subagent turns were mis-tagged.

Fixed at the root rather than re-adding a parallel signal (commit `5e4dbda523`): a subagent conversation's turns now default to `subagentSpawn` when no call site is supplied, derived from the structural `conversation.isSubagent` (set once at spawn, reliable on every run path). So `ctx.callSite` is now correct for queued subagent turns and both nudge plugins' existing `callSite` checks cover them. This also fixes a latent inference bug — those queued turns were resolving under the main config instead of the subagent config. Added a regression test in `conversation-agent-loop-inference-profile.test.ts`.

@codex review

**Comment by siddseethepalli** [comment]
Both addressed in `ce6ae89211`:

**P2 (dynamic-UI gating) — fixed.** You're right, and the cost was bigger than I'd weighed: `supportsDynamicUi: false` covers Telegram/WhatsApp/phone/email (common channels), where `ui_show` is filtered out of the tool set, so weak models there were being coached toward a tool they can't call. Re-exposed `supportsDynamicUi` on `PostToolUseContext` as a host-set turn-capability fact (what the model can *do* this turn, not who's calling), sourced from the conversation's channel via a dependency-free leaf in the daemon run paths (`runAgentLoopImpl` + the wake path) — so it's reliable on every path, including the queue-drain case from the last round. task-progress gates on it (added a 'skips channels without dynamic UI' test).

**P2 (removing `needsFirmerSteering` is breaking) — intentional, and not a real break.** The contract rule is right in general, but this is completing a **same-day revert**: `needsFirmerSteering` shipped in #36436 earlier today and is being removed in this PR before any release could carry it — no external plugin in the current peer range could have adopted a field that existed for a few hours. Treating #36436 + this PR as one add-then-remove wash rather than removing an established field. The whole point (per @dvargasfuertes's review) is that the field shouldn't have been on the shared contract at all.

@codex review

**Comment by siddseethepalli** [comment]
Right again — same root issue as the queued-subagent case, but on the wake path I'd missed. A subagent's background `bash`/`host_bash` completion wakes via `wakeAgentForOpportunity` with no call site, and `agent-wake.ts` resolved its own default to `mainAgent` (separate from the `runAgentLoopImpl` fix). So the subagent wake was mis-tagged: task-progress could nudge it and exploration-drift wouldn't exempt it.

Fixed in `29e009c4d9` by extracting the rule into one shared helper — `resolveTurnCallSite(explicit, conversation)` — and routing **both** daemon run paths (loop + wake) through it, so the subagent→subagentSpawn default can't drift between them again. Added a unit test pinning the rule (explicit passes through; subagent→subagentSpawn; else mainAgent).

@codex review
