### PR TITLE
feat(service-contracts): durable provider-discriminated conversation handles (LUM-2946)

### PR DESCRIPTION
**Pull request by ashleeradka**
## TL;DR

Defines the shared `ConversationHandle` contract in `@vellumai/service-contracts`: a durable, provider-discriminated, JSON-serializable identity for the external provider conversation a Vellum conversation is bound to. The same handle serves inbound conversation binding and later outbound delivery. Schema-only: no runtime behavior, persistence, or adapter changes.

Fixes LUM-2946

## Design

Each variant is a strict Zod object carrying two things: the Vellum channel `connectionId` (the connection/installation identity needed to recover the correct provider credentials) and the provider-native routing coordinates, validated against what the current adapters actually produce:

- **Telegram**: `chatId` plus a `subconversation` union with three distinct variants: `chat`, `message_thread` (Bot API `message_thread_id`: forum topics and private-chat topic mode), and `direct_messages_topic` (Bot API `direct_messages_topic_id`: channel monoforums). These are different Bot API routing fields and the union makes a collapsed or mixed shape unrepresentable.
- **Slack**: `teamId` + `channelId` + optional `threadTs`, matching Slack's native thread keying rather than Telegram's shape.
- **Discord**: `guildId` + `channelId` + optional `threadId` (a thread is itself a channel snowflake), matching the current normalizer's parent-channel/thread split.

Deliberately excluded, per the contract: message ids, reply-to relationships, actors, content, and Vellum's internal `conversationId`. Strict objects reject all of these as unknown keys.

`CONVERSATION_HANDLE_PROVIDERS` is compile-time-asserted to be a subset of the canonical `ChannelId` set, and the schema map's `satisfies Record<...>` clause forces a new provider entry to spell out its shape before it compiles.

## Why this is safe

- Purely additive: a new module, subpath export, and tests. No existing code imports it yet, so no runtime path changes.
- `gateway` and `assistant` both typecheck clean against the updated package.
- 35 new tests cover representative Slack/Telegram/Discord handles round-tripping through serialization and schema parsing, and pin the rejection of cross-provider mixes, mixed Telegram coordinate shapes, flattened untyped topic ids, smuggled message coordinates, and malformed fields.

## What changes for the user

| Before | After |
| ------ | ----- |
| No shared vocabulary for "which provider conversation is this"; each adapter carries its own ad-hoc ids | A single validated contract that later channel-architecture PRs (binding, outbound delivery) build on |
| No user-visible behavior | Unchanged: no user-visible behavior in this PR |

## Out of scope (per the ticket)

- Actor/sender identity, message envelopes, events, capabilities
- Trust, admission, or gateway behavior
- Runtime enforcement, adapter changes, or persisting/migrating Vellum internal conversations

## Notes

- Pre-existing `bunx tsc --noEmit` failures inside `packages/service-contracts` itself (a `normalizePublicBaseUrl` export collision in the aggregate `index.ts` between `ingress.ts` and `remote-web-pairing.ts`, and an extension-less import in `redacted-credential.test.ts`) are untouched; they exist on `main` and are unrelated to this change.
- This replaces the Decision 01 portion of the unmerged LUM-2928 branch (`ashlee-claude/lum-2928-channel-contract-schemas`) per the architecture regroup; that branch's `ChannelAddress` frame is superseded by this shape.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

---

<a href="https://app.devin.ai/review/vellum-ai/vellum-assistant/pull/39677" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open in Devin Review
  </picture>
</a>

### CODE REVIEW

**Comment by ashleeradka** [comment]
Review focus (low risk, additive schema-only PR): the architectural decision worth a human eye is the handle shapes themselves, since later binding/outbound PRs build on them. Specifically: (1) Telegram's three-way subconversation union (chat / message_thread / direct_messages_topic) instead of optional topic fields, (2) keeping Slack threadTs and Discord threadId as plain optionals rather than unions, and (3) connectionId as an opaque Vellum-side identity with no provider-account fields (the prior LUM-2928 branch used provider-native installation ids like botId/teamId in a scope block instead).

File: packages/service-contracts/src/conversation-handle.ts [hunk 1]
```diff
@@ -0,0 +1,246 @@
...
+    );
+
+/** A Slack message timestamp, the thread key (`thread_ts`). */
+const slackThreadTs = () =>
+  z
+    .string()
+    .regex(
+      /^\d{10}\.\d{6}$/,
+      "must be a Slack message timestamp, e.g. 1700000000.000100",
+    );
```
[the remark this answers is not in the document]
Comment (ashleeradka) [reply packages/service-contracts/src/conversation-handle.ts:81]: Confirmed the fallback exists and verified the intended behavior is rejection, not acceptance.

`gateway/src/slack/block-actions-normalizer.ts:79` sets `threadTs: data.message?.thread_ts ?? messageTs ?? envelopeId` on the **reply-routing** field, not on conversation identity. That chain is deliberately about where to post a reply, so it degrades to a message ts and finally an envelope id to keep the reply attached to something. A durable handle is the opposite contract: `threadTs` present must mean "this conversation is a Slack thread rooted at this parent message," and absent must mean "this conversation is the channel itself." An envelope id (a UUID) or a bare message ts in that slot would mint a distinct durable identity for what is really the same channel conversation, so the strict `\d{10}\.\d{6}` regex rejecting them is the intended behavior rather than an oversight.

So the binding layer must use raw `thread_ts` only and omit the field when it is absent, never the routing fallback. Pinned that expectation with a test case asserting an envelope-id-shaped `threadTs` fails validation, in 92e0ac1328. The bare-`messageTs` case was already covered by the existing `messageTs` rejection case in the same file.

Note that a real `thread_ts` and a real `messageTs` are the same lexical shape, so the schema cannot distinguish them; that one stays a binding-layer obligation, which this PR does not implement. Worth re-checking when the binding PR lands.
